packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  vue-demi: true
  "@tailwindcss/oxide": true
  prisma: true
  "@prisma/client": true
  sharp: true
  workbox-build: true
  '@prisma/engines': true
  '@scarf/scarf': false
